const data = [
  {
    id: 1,
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS33DWHodvlDR_SOCQyYyqrb9Td8hvufc3zYCnnAD4PkBX4W7dF",
    title: "John Wick 4",
    desc: "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    genre: "Action, Thriller, Crime",
    cast: "Hiroyuki Sanada, Natalia Tena, Keanu Reeves, Rina Sawayama, Lance Reddick",
    price: "250.00",
  },
  {
    id: 2,
    img: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSGQUTaBL19fLf8caYxcyNt0mYl9HgpiKPAaGgQxCuz3ZTvAWVI",
    title: "Avatar: The Way of Water",
    desc: "Set more than a decade after the events of the first film, “Avatar: The Way of Water” begins to tell the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    genre: "Action, Fantasy, Science Fiction, Adventure",
    cast: "Zoe Saldana, Sam Worthington, Kate Winslet, Stephen Lang, Oona Chaplin",
    price: "250.00",
  },
  {
    id: 3,
    img: "https://movies.universalpictures.com/media/fstx-montage1sheet2-rgb-1-64108e93e63dd-1.jpg",
    title: "Fast X",
    desc: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted and outdriven every foe in their path. Now, they must confront the most lethal opponent they've ever faced. Fueled by revenge, a terrifying threat emerges from the shadows of the past to shatter Dom's world and destroy everything and everyone he loves.",
    genre: "Action, Crime, Thriller",
    cast: "Vin Diesel, Gal Gadot, Ludacris, Daniela Melchior, Scott Eastwood",
    price: "300.00",
  },
  {
    id: 4,
    img: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcS1razy4eSumpLe0M2KOCN-tJMiCUsIfPwH3SKH1h3jZE4t2v-D",
    title: "The Little Mermaid",
    desc: "The youngest of King Triton’s daughters, and the most defiant, Ariel longs to find out more about the world beyond the sea, and while visiting the surface, falls for the dashing Prince Eric. With mermaids forbidden to interact with humans, Ariel makes a deal with the evil sea witch, Ursula, which gives her a chance to experience life on land, but ultimately places her life and her father’s crown  in jeopardy.",
    genre: "Adventure, Family, Fantasy, Romance",
    cast: "Jonah Hauer-King, Halle Bailey, Daveed Diggs, Jacob Tremblay, Awkwafina",
    price: "300.00",
  },
  {
    id: 5,
    img: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQoqCeUmQj_C0YYZlSkXVwDwv1566jncQzZMJEMxDcThPkAefrE",
    title: "Guardians of the Galaxy Vol. 3",
    desc: "Still reeling from the loss of Gamora, Peter Quill must rally his team to defend the universe and protect one of their own. If the mission is not completely successful, it could possibly lead to the end of the Guardians as we know them.",
    genre: "Action, Adventure, Science Fiction, Comedy",
    cast: "Chris Pratt, Bradley Cooper, Vin Diesel, Dave Bautista, Pom Klementieff",
    price: "300.00",
  },
];
export default data;
